spring.application.name=campusmarketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/campus_marketplace
spring.datasource.username=postgres
spring.datasource.password=Harshitha@20

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379